### ISSUE TITLE
"Unsuitable transport selected " on Hangup

### ISSUE THREAD

**Issue by SafinRR** [siniypin/pjsip4net#30] opened 2015-06-10 10:56 UTC
![call](https://cloud.githubusercontent.com/assets/4506442/8080786/c9f510f2-0f88-11e5-8d2a-ebbc3e1d1e32.jpg)
Hello!
I canot hangup a call.  Exception:
{"PJSIP error code =  15:08:45.280   pjsua_call.c  Failed to send end session message: Unsuitable transport selected (PJSIP_ETPNOTSUITABLE) [status=171064]\n in HangupCall"}

code

    XmlConfigurator.Configure();
            _logger = LogManager.GetLogger("root");//logging is purely an application facility, you can choose whatever you want to log with
            var container = new WindsorContainer();
            var cfg = Configure.Pjsip4Net()//dynamically discovers interop assembly and loads API providers unless concrete version loader specified
                .With_CastleContainer(container)//plugs an existing DI-container
                .FromConfig();//read configuration from .config file 
            ua = cfg.Build().Start();//build and start
            ua.ImManager.IncomingMessage += IncomingMessage;
            ua.CallManager.CallRedirected += CallRedirected;
            ua.CallManager.IncomingDtmfDigit += IncomingDtmfDigit;
            ua.ImManager.NatDetected += OnNatDetected;
            ua.CallManager.IncomingCall += CallManager_IncomingCall;
            ua.CallManager.CallStateChanged += CallManager_CallStateChanged;
            UA_container = cfg.Container;
            var account = ua.AccountManager.Accounts[0];
            var call = ua.CallManager.MakeCall(account, "sip:sip@bee.contentum-it.ru:5060");
            var factory = new CommandFactory(ua, UA_container);
            factory.Create("?").Execute();
            

            while (true)
            {
                try
                {
                    var line = System.Console.ReadLine();
                    if (string.IsNullOrEmpty(line))
                        break;
                    var command = factory.Create(line);
                    command.Execute();
                     
                }
                catch (PjsipErrorException ex)
                {
                    System.Console.WriteLine(ex.Message);
                }
                catch (SystemException ex)
                {
                    System.Console.WriteLine(ex.Message);
                }
            }
            ua.Destroy();
        }

        static void CallManager_CallStateChanged(object sender, CallStateChangedEventArgs e)
        {
            System.Console.WriteLine("Call to {0}: {1}", e.DestinationUri, e.Duration);
            if (e.InviteState == InviteState.Confirmed && e.MediaState == CallMediaState.Active)
            {
                
                pjsip4net.Interfaces.ICallManager callmanager = (pjsip4net.Interfaces.ICallManager)sender ;
                ICall call = callmanager.Calls[e.Id];
                call.Hangup();
            }
            

        }
 LOG

2015-06-10 15:08:41,778 [10] DEBUG -  15:08:41.778   pjsua_core.c  RX 531 bytes
Response msg 401/INVITE/cseq=5469 (rdata0D0001F8) from tcp 192.168.115.30:5060:
SIP/2.0 401 Unauthorized
Via: SIP/2.0/tcp 192.168.115.30:56491;rport;branch=z9hG4bKPjd39763e9fe63491fbaea
8ffc10ce1181
From:  sip:test@bee.contentum-it.ru;tag=3c91c1253df24aeead019120e981858c
To:  sip:sip@bee.contentum-it.ru;tag=93bfea0b1ff94db5ae9244505a134ecc
Call-ID: 0c16369d7e1d492eb218cc474dd57962
CSeq: 5469 INVITE
x-Error-Details: No auth header
WWW-Authenticate: Digest realm="bee.contentum-it.ru",nonce="c9171ac1cb61af6118a9
fb8f7821ef0d",qop="auth",algorithm=MD5,stale=false,opaque="0000000d"
Content-Length: 0

--end msg--

2015-06-10 15:08:41,781 [10] DEBUG -  15:08:41.779   pjsua_core.c  TX 396 bytes
Request msg ACK/cseq=5469 (tdta0D001C58) to tcp 192.168.115.30:5060:
ACK sip:sip@bee.contentum-it.ru:5060;transport=TCP SIP/2.0
Via: SIP/2.0/tcp 192.168.115.30:56491;rport;branch=z9hG4bKPjd39763e9fe63491fbaea
8ffc10ce1181
Max-Forwards: 70
From: sip:test@bee.contentum-it.ru;tag=3c91c1253df24aeead019120e981858c
To: sip:sip@bee.contentum-it.ru;tag=93bfea0b1ff94db5ae9244505a134ecc
Call-ID: 0c16369d7e1d492eb218cc474dd57962
CSeq: 5469 ACK
Content-Length:  0

--end msg--

2015-06-10 15:08:41,782 [10] DEBUG -  15:08:41.782   tcpc0D00347C  TCP client tr
ansport created

2015-06-10 15:08:41,783 [10] DEBUG -  15:08:41.783   tcpc0D00347C  TCP transport
 192.168.115.30:56492 is connecting to 192.168.115.30:5060...

2015-06-10 15:08:41,783 [10] DEBUG -  15:08:41.783   pjsua_core.c  TX 1395 bytes
 Request msg INVITE/cseq=5470 (tdta0BFBD340) to tcp 192.168.115.30:5060:
INVITE sip:sip@bee.contentum-it.ru:5060;transport=TCP SIP/2.0
Via: SIP/2.0/tcp 192.168.115.30:56492;rport;branch=z9hG4bKPja0fd8cf423654a48998b
8598d3ab304c
Max-Forwards: 70
From: sip:test@bee.contentum-it.ru;tag=3c91c1253df24aeead019120e981858c
To: sip:sip@bee.contentum-it.ru
Contact: <sip:test@192.168.9.49:5080;transport=TCP>
Call-ID: 0c16369d7e1d492eb218cc474dd57962
CSeq: 5470 INVITE
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, SUBSCRIBE, NOTIFY, REFER, MESSAG
E, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800
Min-SE: 90
Authorization: Digest username="test", realm="bee.contentum-it.ru", nonce="c9171
ac1cb61af6118a9fb8f7821ef0d", uri="sip:sip@bee.contentum-it.ru:5060;transport=TC
P", response="fa4a010508fa1be83c6689a6aade4045", algorithm=MD5, cnonce="a3e2ab5d
46fb4176a4cd4474f2aebe83", opaque="0000000d", qop=auth, nc=00000001
Content-Type: application/sdp
Content-Length:   459

v=0
o=- 3642937721 3642937721 IN IP4 192.168.9.49
s=pjmedia
c=IN IP4 192.168.9.49
t=0 0
a=X-nat:0
m=audio 4008 RTP/AVP 103 102 104 113 3 0 8 9 101
a=rtcp:4009 IN IP4 192.168.9.49
a=rtpmap:103 speex/16000
a=rtpmap:102 speex/8000
a=rtpmap:104 speex/32000
a=rtpmap:113 iLBC/8000
a=fmtp:113 mode=30
a=rtpmap:3 GSM/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=sendrecv
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15

--end msg--

2015-06-10 15:08:41,787 [10] DEBUG -  15:08:41.787   tcpc0D00347C  TCP transport
 192.168.115.30:56492 is connected to 192.168.115.30:5060

2015-06-10 15:08:41,788 [10] DEBUG -  15:08:41.788   pjsua_core.c  RX 305 bytes
Response msg 100/INVITE/cseq=5470 (rdata0D003618) from tcp 192.168.115.30:5060:
SIP/2.0 100 Trying
Via: SIP/2.0/tcp 192.168.115.30:56492;rport;branch=z9hG4bKPja0fd8cf423654a48998b
8598d3ab304c
From:  sip:test@bee.contentum-it.ru;tag=3c91c1253df24aeead019120e981858c
To:  sip:sip@bee.contentum-it.ru
Call-ID: 0c16369d7e1d492eb218cc474dd57962
CSeq: 5470 INVITE
Content-Length: 0

--end msg--

2015-06-10 15:08:42,394 [10] DEBUG -  15:08:42.394   pjsua_core.c  RX 352 bytes
Response msg 100/INVITE/cseq=5470 (rdata0D003618) from tcp 192.168.115.30:5060:
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 192.168.115.30:56492;rport;branch=z9hG4bKPja0fd8cf423654a48998b
8598d3ab304c
Record-Route: <sip:192.168.115.30:5060;lr>
Call-ID: 0c16369d7e1d492eb218cc474dd57962
From: <sip:test@bee.contentum-it.ru>;tag=3c91c1253df24aeead019120e981858c
To: <sip:sip@bee.contentum-it.ru>
CSeq: 5470 INVITE
Content-Length:  0

--end msg--

2015-06-10 15:08:42,502 [10] DEBUG -  15:08:42.502   pjsua_core.c  RX 542 bytes
Response msg 180/INVITE/cseq=5470 (rdata0D003618) from tcp 192.168.115.30:5060:
SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 192.168.115.30:56492;rport;branch=z9hG4bKPja0fd8cf423654a48998b
8598d3ab304c
Record-Route: <sip:192.168.115.30:5060;lr>
Call-ID: 0c16369d7e1d492eb218cc474dd57962
From: <sip:test@bee.contentum-it.ru>;tag=3c91c1253df24aeead019120e981858c
To: <sip:sip@bee.contentum-it.ru>;tag=ivo4DRK97ndzsjGBUbh5LHB-.isj2FJp
CSeq: 5470 INVITE
Contact: <sip:sip@192.168.115.30:5060;transport=tcp>
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER,
MESSAGE, OPTIONS
Content-Length:  0

--end msg--

2015-06-10 15:08:44,463 [11] DEBUG -  15:08:44.461    udp0BE3E4F0  Remote RTCP a
ddress switched to 192.168.9.43:4001

2015-06-10 15:08:45,261 [10] DEBUG -  15:08:45.261   pjsua_core.c  RX 935 bytes
Response msg 200/INVITE/cseq=5470 (rdata0D003618) from tcp 192.168.115.30:5060:
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.115.30:56492;rport;branch=z9hG4bKPja0fd8cf423654a48998b
8598d3ab304c
Record-Route: <sip:192.168.115.30:5060;lr>
Call-ID: 0c16369d7e1d492eb218cc474dd57962
From: <sip:test@bee.contentum-it.ru>;tag=3c91c1253df24aeead019120e981858c
To: <sip:sip@bee.contentum-it.ru>;tag=ivo4DRK97ndzsjGBUbh5LHB-.isj2FJp
CSeq: 5470 INVITE
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER,
MESSAGE, OPTIONS
Contact: <sip:sip@192.168.115.30:5060;transport=tcp>
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800;refresher=uac
Require: timer
Content-Type: application/sdp
Content-Length:   263

v=0
o=- 3642919721 3642919722 IN IP4 192.168.9.43
s=pjmedia
c=IN IP4 192.168.9.43
t=0 0
m=audio 4000 RTP/AVP 0 101
c=IN IP4 192.168.9.43
a=rtcp:4001 IN IP4 192.168.9.43
a=sendrecv
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16

--end msg--

2015-06-10 15:08:45,263 [10] DEBUG - Call 0 ConnectingInviteState
Call to sip:sip@bee.contentum-it.ru:5060;transport=TCP: 00:00:03.7560000
2015-06-10 15:08:45,264 [10] DEBUG -  15:08:45.264   strm0D0059EC  VAD temporari
ly disabled

2015-06-10 15:08:45,264 [10] DEBUG -  15:08:45.264   strm0D0059EC  Encoder strea
m started

2015-06-10 15:08:45,264 [10] DEBUG -  15:08:45.264   strm0D0059EC  Decoder strea
m started

2015-06-10 15:08:45,265 [10] DEBUG -  15:08:45.265  pjsua_media.c  Media updates
, stream #0: PCMU (sendrecv)

2015-06-10 15:08:45,267 [10] DEBUG - Call 0 ActiveMediaState
2015-06-10 15:08:45,268 [10] DEBUG -  15:08:45.268   conference.c  Port 1 (sip:s
ip@bee.contentum-it.ru:5060;transport=TCP) transmitting to port 0 (Первичный дра
йвер записи звука)

2015-06-10 15:08:45,269 [10] DEBUG -  15:08:45.269   conference.c  Port 0 (Перви
чный драйвер записи звука) transmitting to port 1 (sip:sip@bee.contentum-it.ru:5
060;transport=TCP)

Call to sip:sip@bee.contentum-it.ru:5060;transport=TCP: 00:00:03.7600000
2015-06-10 15:08:45,270 [10] DEBUG - Call 0 ConfirmedInviteState
Call to sip:sip@bee.contentum-it.ru:5060;transport=TCP: 00:00:03.7640000
pjsip4net.Calls.DefaultCallManager
2015-06-10 15:08:45,273 [10] WARN  -  15:08:45.273    tsx0D00A0F4  Failed to sen
d Request msg BYE/cseq=5471 (tdta0D009088)! err=171064 (Unsuitable transport sel
ected (PJSIP_ETPNOTSUITABLE))

2015-06-10 15:08:45,274 [10] DEBUG - Call 0 DisconnectedInviteState
2015-06-10 15:08:45,278 [10] DEBUG - Call 0 disposed
Call to sip:sip@bee.contentum-it.ru:5060;transport=TCP: 00:00:03.7670000
2015-06-10 15:08:45,280 [10] DEBUG -  15:08:45.280  pjsua_media.c  Media session
 for call 0 is destroyed

2015-06-10 15:08:45,280 [10] ERROR -  15:08:45.280   pjsua_call.c  Failed to sen
d end session message: Unsuitable transport selected (PJSIP_ETPNOTSUITABLE) [sta
tus=171064]

_______________________________________________________
config
  
     <sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="true" autoRecording="false" autoConference="false" maxCalls="110">
     <accounts>
      <account accountId="sip:test@bee.contentum-it.ru" registrarUri="sip:bee.contentum-it.ru:5060;transport=tcp"
    userName="test" password="123" realm="bee.contentum-it.ru" isDefault="false"
    publishPresence="true" />

      
    </accounts>
    <sipTransport type="tcp" Port="5080"/>
    <networkSettings natInSDP="true" forceLooseRoute="false">
      
      <turn enabled="false" server="" type="udp" userName="" password="" realm=""/>
      <ice enabled="false" noRTCP="false"/>
      
    </networkSettings>
    <media isVADEnabled="true" playbackDeviceId="9" captureDeviceId="6"/>
  </sipua>

**Comment by siniypin** [comment] 2015-06-11 09:08
Hello, 

first let's figure out what setup do you have. There is a registrar server, that holds the directory of extensions (bee.contentum-it.ru which resolves to 192.168.115.30 I suppose). Both parties register with this server, then one of them initiates a call to another (who resides on device with ipv4: 192.168.9.43) via registrar server (sip:sip@bee.contentum-it.ru:5060;transport=TCP). Media stream is transferred directly and registrar server doesn't proxy it. All components are within a single subnet. 
Are all of my assumptions correct?

Can you please try to reproduce this scenario with p2p call setup (with no registrar server proxying session messages exchange)? You can use a local default accounts with id 0 for that, i.e. make a call to sip:0@192.168.9.43:<port client started on>;transport=tcp from account with id 0.

What registrar server do you use? Is it properly configured?

Cheers.

**Comment by siniypin** [comment] 2015-06-11 09:10
You can also try to set your registrar as outbound proxy in ua config. This option is available both via .config file or via code configuration.

**Comment by SafinRR** [comment] 2015-06-11 13:05
I am use OffiseSip Server. 
Explain how can  I configure p2p call, please. Or where can I read about this.

Can  be error  cause  in upper case  value of read only property Call.DestinationUri  (transport=TCP)?

**Comment by siniypin** [comment] 2015-06-11 13:55
You don't have to configure anything. P2P call basically refers to a scenario when SIP clients reach each other directly, without registration at SIP registrar server (only applicable when addresses are fixed). The problem is most likely somewhere at the differences between server and client implementation (pjsip4net uses pjsip 1.4 underneath and it is rather old and misses lots of bug fixes from latest versions). In order to prove this assumption, I want you to make a direct call.
Start with no accounts specified, make a call with [DefaultAccount] (https://github.com/siniypin/pjsip4net/blob/d51fbea9c47d87d7177f6aaf4face362686f33c3/pjsip4net/Interfaces/IAccountManager.cs#L16) specified as the originator of call, a destination extension could be any arbitrary string, provided it is a valid string according to SIP uri rules. The domain and port parts of SIP uri must match the other party's host and port. Transports must match too. 
BTW do both parties register with the same SIP transport?

**Comment by siniypin** [comment] 2015-06-12 10:02
Oh sorry, I've missed your previous reply. OK, so it IS something between the server and client library. 
Do both parties register with TCP SIP transport?
Have you tried to specify your registrar server as outbound proxy?

Can I ask you to reproduce your test case with pjsua.exe app? I will upload a corresponding binary file tomorrow.

**Comment by SafinRR** [comment] 2015-06-13 09:46
I am new for sip and voip. And a don`not understand some things.
 How can i do test with outbound proxy?
"Do both parties register with TCP SIP transport?" - I think yes :) . in .config i setup tcp? and destination uri include transport=tcp.

pjsua.exe - ок. Where is it and what to do?

**Comment by siniypin** [comment] 2015-06-15 20:26
Please find a corresponding pjsua binary with this commit b02313f4369813de24a5edb94c0e49279524ddbf 
The documentation for this console sip user agent can be found [here](http://www.pjsip.org/pjsua.htm).
With this tool you can reproduce your scenario and verify if native pjsip app has the same problem or not. 

Cheers

**Comment by SafinRR** [comment] 2015-06-16 06:42
Hello!  test working well. Hangup successfull

conf:
# This is a comment in the config file.
--id sip:test@bee.contentum-it.ru
--registrar sip:bee.contentum-it.ru:5060;transport=tcp
--realm bee.contentum-it.ru
--username test
--password 123
--local-port=5070


D:\srr\prj\vstudio\SIP\pjsip triks\test_bin>pjsua-i386-Win32-vc8-Debug.exe --con
fig-file conf
 11:36:41.283   pjsua_core.c  pjsua version 1.4 for win32 initialized
 11:36:41.299    pjsua_acc.c  Registration sent
>>>>
 11:36:41.321    pjsua_acc.c  IP address change detected for account 2 (192.168.
9.49:5070 --> 192.168.9.49:46402). Updating registration..
 11:36:41.322    pjsua_acc.c  Unregistration sent
 11:36:41.323    pjsua_acc.c  Registration sent
Account list:
  [ 0] <sip:192.168.9.49:5070>: does not register
       Online status: Online
  [ 1] <sip:192.168.9.49:5070;transport=TCP>: does not register
       Online status: Online
 *[ 2] sip:test@bee.contentum-it.ru: 100/In Progress (expires=0)
       Online status: Online
Buddy list:
 -none-

+=============================================================================+
|       Call Commands:         |   Buddy, IM & Presence:  |     Account:      |
|                              |                          |                   |
|  m  Make new call            | +b  Add new buddy       .| +a  Add new accnt |
|  M  Make multiple calls      | -b  Delete buddy         | -a  Delete accnt. |
|  a  Answer call              |  i  Send IM              | !a  Modify accnt. |
|  h  Hangup call  (ha=all)    |  s  Subscribe presence   | rr  (Re-)register |
|  H  Hold call                |  u  Unsubscribe presence | ru  Unregister    |
|  v  re-inVite (release hold) |  t  ToGgle Online status |  >  Cycle next ac.|
|  U  send UPDATE              |  T  Set online status    |  <  Cycle prev ac.|
 11:36:41.325    pjsua_acc.c  sip:test@bee.contentum-it.ru: registration success
, status=200 (OK), will re-register in 300 seconds
| ],[ Select next/prev call    +--------------------------+-------------------+
|  x  Xfer call                |      Media Commands:     |  Status & Config: |
|  X  Xfer with Replaces       |                          |                   |
|  #  Send RFC 2833 DTMF       | cl  List ports           |  d  Dump status   |
|  *  Send DTMF with INFO      | cc  Connect port         | dd  Dump detailed |
| dq  Dump curr. call quality  | cd  Disconnect port      | dc  Dump config   |
|                              |  V  Adjust audio Volume  |  f  Save config   |
|  S  Send arbitrary REQUEST   | Cp  Codec priorities     |  f  Save config   |
+------------------------------+--------------------------+-------------------+
|  q  QUIT   L  ReLoad   sleep MS   echo [0|1|txt]     n: detect NAT type     |
+=============================================================================+
You have 0 active call
>>> m
(You currently have 0 calls)
Buddy list:
 -none-

Choices:
   0         For current dialog.
  -1         All 0 buddies in buddy list
  [1 - 0]    Select from buddy list
  URL        An URL
  <Enter>    Empty input (or 'q') to cancel
Make call: sip:sip@bee.contentum-it.ru
 11:36:50.628    pjsua_app.c  Call 0 state changed to CALLING
>>>  11:36:50.645    pjsua_app.c  Call 0 state changed to CALLING
 11:36:50.828    pjsua_app.c  Call 0 state changed to EARLY (180 Ringing)
 11:36:57.251    pjsua_app.c  Call 0 state changed to CONNECTING
 11:36:57.251    pjsua_app.c  Media for call 0 is active
 11:36:57.252    pjsua_app.c  Call 0 state changed to CONFIRMED
h
>>>  11:37:06.852    pjsua_app.c  Call 0 is DISCONNECTED [reason=200 (Normal cal
l clearing)]
 11:37:06.852    pjsua_app.c
  [DISCONNCTD] To: sip:sip@bee.contentum-it.ru;tag=2GHoO8jNSq52Gz7KYqWhpxvFtOQWL
lER
    Call time: 00h:00m:09s, 1st res in 200 ms, conn in 6624ms
    SRTP status: Not active Crypto-suite: (null)
    #0 PCMU @8KHz, sendrecv, peer=192.168.9.43:4004
       RX pt=0, stat last update: 00h:00m:04.766s ago
          total 481pkt 76.9KB (96.2KB +IP hdr) @avg=64.1Kbps/80.1Kbps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.925  13.125   1.250   1.638
       TX pt=0, ptime=20ms, stat last update: 00h:00m:04.240s ago
          total 215pkt 34.4KB (43.0KB +IP hdr) @avg 28.6Kbps/35.8Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.375   0.750   0.750   0.375
      RTT msec       :   1.296   2.592   3.888   3.888   1.296

**Comment by siniypin** [comment] 2015-06-16 08:33
Awesome, than the problem is with pjsip4net. Can you possibly capture the SIP traffic with both of clients? I need as much log data as possible for both successful and unsuccessful calls as I can't obviously connect to your server.

**Comment by SafinRR** [comment] 2015-06-16 10:00
wireshark?

**Comment by siniypin** [comment] 2015-06-16 10:38
This https://github.com/siniypin/pjsip4net/blob/d51fbea9c47d87d7177f6aaf4face362686f33c3/pjsip4net.Core/Data/LoggingConfig.cs#L5 and this http://www.pjsip.org/docs/latest-1/pjsip/docs/html/structpjsua__logging__config.htm#a2714be20ad8d2f954789f93aacfb19b5
set to `true` and this https://github.com/siniypin/pjsip4net/blob/d51fbea9c47d87d7177f6aaf4face362686f33c3/pjsip4net.Core/Data/LoggingConfig.cs#L6 and this http://www.pjsip.org/docs/latest-1/pjsip/docs/html/structpjsua__logging__config.htm#aef4b96f808214ab8e273b69f3e8efa54
set to `6` should do the trick.

**Comment by SafinRR** [comment] 2015-06-16 11:53
I cannot setup level 6. My app throw exception on  logLevel="5" in  app.cpnfig. Lecel 5 is maximum. A get logs from registrar server.How can i send  you 2 log files?

**Comment by SafinRR** [comment] 2015-06-16 12:11
Log from registrar

2015-06-16 15:38 GMT+05:00 Robert <notifications@github.com>:

**Comment by siniypin** [comment] 2015-06-16 13:36
Please send them to my private email (github user name) at gmail dot com.

**Comment by siniypin** [comment] 2015-06-16 20:24
The caller registers with TCP, whereas the callee registers with UDP transport. After the session  established no other messages being sent via registrar server. That means the caller tries to close the session by sending a message to callee directly. However, they use different transports and that is why you get this error message. 
You should specify your registrar server as outbound proxy to send SIP messages via always to avoid this transport mismatch. That should do the trick. You can configure it either in config file or directly in code. Please find examples below: 
https://gist.github.com/siniypin/7860029
https://gist.github.com/siniypin/7860386

**Comment by SafinRR** [comment] 2015-06-17 06:12
Am I have to delete configuration of accounts from config?
conf: 
  <proxies>
      <add address="sip:bee.contentum-it.ru:5060;transport=tcp" />
    </proxies>      
code:
 var call =  ua.CallManager.MakeCall("sip:sip@192.168.9.49:5060;transport=tcp");

if i do  that i recive:

2015-06-17 10:59:35,337 [4] DEBUG -  10:59:35.336   pjsua_core.c  RX 513 bytes R
esponse msg 401/INVITE/cseq=25889 (rdata0A88CBF8) from tcp 192.168.9.49:5060:
SIP/2.0 401 Unauthorized
Via: SIP/2.0/tcp 192.168.9.49:55989;rport;branch=z9hG4bKPj6bc344685588497999e89e
7f894c53d1
From:  <sip:192.168.9.49>;tag=7a360eac95ca48388ea816cf9cffdb35
To:  sip:sip@192.168.9.49;tag=f6644a0528624a2b9924e7f815709fc0
Call-ID: 8e2ee14c4ece476496dd06b99ab3a060
CSeq: 25889 INVITE
x-Error-Details: No auth header
WWW-Authenticate: Digest realm="bee.contentum-it.ru",nonce="87465dcd09aeeab0a00b
2b194c1d3d47",qop="auth",algorithm=MD5,stale=false,opaque="0000000c"
Content-Length: 0
--end msg--

**Comment by siniypin** [comment] 2015-06-17 08:08
You shouldn't delete them if you want to register with your Registrar server and make calls to other registered users. Leave your accounts, just add outbound proxy to make sure all the session traffic is proxied by your server.

**Comment by siniypin** [comment] 2015-06-17 20:44
@SafinRR
So, did you manage to hangup the call normally?

**Comment by SafinRR** [comment] 2015-06-18 09:14
Hello!
No, proxy did not solve hangup problem in my configuration ( OfficeSip + Android sip client). But it was test enviroment. I connected to commercial  SIP server and call to real GSM phones - everything  works well. So now it`s not actual problem.

Tell me , please, in   CallStateChanged event     CallStateChangedEventArgs e.id - it`s not id of Call in  (pjsip4net.Interfaces.ICallManager)sender ?

**Comment by siniypin** [comment] 2015-06-18 11:31
It is always an identifier of a call managed by ICallManager (an artificial integer id). If you need access to any call related data you can get it using ICall interface. BTW, I have a pull request to make a CallInfo access public, which I am about to merge shortly #29 (it is mixed up with nuget stuff as well, I am going to pick it all manually).

Alright, I'll try to investigate this issue a bit with my local FreeSwitch server, however there is no guarantee that it'll have the same behaviour. Closing the issue for now.

**Closed by siniypin** 2015-06-18 11:31 UTC
Labels: bug

**Comment by guilledefino** [comment] 2019-10-21 20:37
Hello!
I am using pjsip4net library to develop an contact-id receiver which receive alarms. when alarm device sends an alarm, dtmf numbers are transmitting too fast and library does not recognize numbers as DTMF instead audio.
can you help me to solve this problem?

thanks in advance
Billy

**Comment by siniypin** [comment] 2019-10-22 09:22
I'm sorry, but I don't understand your problem and thus can't help you.
